apiVersion: v1
kind: ConfigMap
metadata:
  name: opsboard-config
  namespace: opsboard
  labels:
    app.kubernetes.io/name: opsboard
data:
  NODE_ENV: "production"
  # In production, we could e.g. use Bitwarden Secret Manager and the k8s operator to inject secrets securely in the Pod.
  # The Operator would inject the password as an environment variable.
  DATABASE_URL: "postgresql://user:password@db-host:5432/opsboard"
  NEXT_TELEMETRY_DISABLED: "1"
