apiVersion: v1
kind: Service
metadata:
  name: opsboard
  namespace: opsboard
  labels:
    app.kubernetes.io/name: opsboard
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: opsboard
